version: "3.1"

services:
  db:
    image: mysql:8.2
    environment:
      MYSQL_DATABASE: metrics
      MYSQL_USER: monitor
      MYSQL_PASSWORD: monitor
      MYSQL_RANDOM_ROOT_PASSWORD: true
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 3s
      timeout: 5s
      retries: 10
